version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always

  minio:
    image: quay.io/minio/minio
    container_name: minio1
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - D:/minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
